postgres_service:
  build: ./db
#  expose:
#   - "8080"
  ports:
    - '1515:5432'
  volumes:
    - ./init:/dockypoint-initdb.d/

tomcat_service:
  build: ./web
  ports:
    - "8081:8080"
  links:
    - postgres_service

#tomcat_service_jar:
#  build: ./webjar
#  ports:
#    - "8080:8080"
#  links:
#    - postgres_service